### ISSUE TITLE
Wallet balance

### ISSUE THREAD

**Issue by radulucaciu** [jozsi/wealthor#41]
It's such a cool feature to be able to set the initial value of a wallet.

The issue is that, should we ever need to sync (for whatever reason) the transactions with the wallet - we'd be in trouble because the original initial value has been overridden when new transactions we added.

I suggest storing this initial value in a separate variable within the wallet model

**Comment by jozsi** [comment]
Done via 1e029bf3ba5fc3c4b8a490af7e5ac39460ba2737 - it's being saved as `initialBalance`
