### ISSUE TITLE
Default categories

### ISSUE THREAD

**Issue by radulucaciu** [jozsi/wealthor#59]
Let's add some default categories for new users
- Travel
- Entertainment
- Transportation
- Eating out
- Medical
- Clothes
- Groceries
- Rent
- Services

**Comment by radulucaciu** [comment]
I think these might already be implemented.

**Comment by jozsi** [comment]
Yep, we do have the following list implemented: https://github.com/jozsi/mystash/blob/master/src/backend/factories/categories.js#L1-L27

We can trim it down to a smaller number, more relevant categories, like the ones above. If you wish to do this, please re-open the issue.
